[package]
name = "netvm"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2
strip = "symbols"
lto = true
panic = "abort"

[profile.release]
opt-level = 2
strip = "symbols"
lto = true
panic = "abort"

[dependencies]
